version: '3.8'

services:
  moviesapi:
    build:
      context: ./MoviesAPI
      dockerfile: Dockerfile
    ports:
      - '5001:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  moviesweb:
    build:
      context: ./MoviesWeb
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
